// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.2
// source: cinema.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//返回影院数据
type CinemaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaId   string `protobuf:"bytes,1,opt,name=cinema_id,json=cinemaId,proto3" json:"cinema_id,omitempty"`
	CinemaName string `protobuf:"bytes,2,opt,name=cinema_name,json=cinemaName,proto3" json:"cinema_name,omitempty"`
	Remark     string `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
}

func (x *CinemaResponse) Reset() {
	*x = CinemaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CinemaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CinemaResponse) ProtoMessage() {}

func (x *CinemaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CinemaResponse.ProtoReflect.Descriptor instead.
func (*CinemaResponse) Descriptor() ([]byte, []int) {
	return file_cinema_proto_rawDescGZIP(), []int{0}
}

func (x *CinemaResponse) GetCinemaId() string {
	if x != nil {
		return x.CinemaId
	}
	return ""
}

func (x *CinemaResponse) GetCinemaName() string {
	if x != nil {
		return x.CinemaName
	}
	return ""
}

func (x *CinemaResponse) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

// 返回影院集合
type CinemaListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaResponse []*CinemaResponse `protobuf:"bytes,1,rep,name=cinema_response,json=cinemaResponse,proto3" json:"cinema_response,omitempty"`
}

func (x *CinemaListResponse) Reset() {
	*x = CinemaListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CinemaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CinemaListResponse) ProtoMessage() {}

func (x *CinemaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CinemaListResponse.ProtoReflect.Descriptor instead.
func (*CinemaListResponse) Descriptor() ([]byte, []int) {
	return file_cinema_proto_rawDescGZIP(), []int{1}
}

func (x *CinemaListResponse) GetCinemaResponse() []*CinemaResponse {
	if x != nil {
		return x.CinemaResponse
	}
	return nil
}

//根据影院ID请求
type CinemaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CinemaId string `protobuf:"bytes,1,opt,name=cinema_id,json=cinemaId,proto3" json:"cinema_id,omitempty"`
}

func (x *CinemaRequest) Reset() {
	*x = CinemaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CinemaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CinemaRequest) ProtoMessage() {}

func (x *CinemaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CinemaRequest.ProtoReflect.Descriptor instead.
func (*CinemaRequest) Descriptor() ([]byte, []int) {
	return file_cinema_proto_rawDescGZIP(), []int{2}
}

func (x *CinemaRequest) GetCinemaId() string {
	if x != nil {
		return x.CinemaId
	}
	return ""
}

//根据地域请求该地域下的影院
type RegionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CityId   int32   `protobuf:"varint,1,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty"`
	CountyId int32   `protobuf:"varint,2,opt,name=county_id,json=countyId,proto3" json:"county_id,omitempty"`
	Type     string  `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Lat      float32 `protobuf:"fixed32,4,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon      float32 `protobuf:"fixed32,5,opt,name=lon,proto3" json:"lon,omitempty"`
	PageNum  int32   `protobuf:"varint,6,opt,name=page_num,json=pageNum,proto3" json:"page_num,omitempty"`
	PageSize int32   `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *RegionRequest) Reset() {
	*x = RegionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cinema_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegionRequest) ProtoMessage() {}

func (x *RegionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cinema_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegionRequest.ProtoReflect.Descriptor instead.
func (*RegionRequest) Descriptor() ([]byte, []int) {
	return file_cinema_proto_rawDescGZIP(), []int{3}
}

func (x *RegionRequest) GetCityId() int32 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *RegionRequest) GetCountyId() int32 {
	if x != nil {
		return x.CountyId
	}
	return 0
}

func (x *RegionRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RegionRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *RegionRequest) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *RegionRequest) GetPageNum() int32 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *RegionRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

var File_cinema_proto protoreflect.FileDescriptor

var file_cinema_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1b,
	0x64, 0x75, 0x62, 0x62, 0x6f, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x66, 0x0a, 0x0e, 0x43,
	0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x69,
	0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72,
	0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d,
	0x61, 0x72, 0x6b, 0x22, 0x6a, 0x0a, 0x12, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x54, 0x0a, 0x0f, 0x63, 0x69, 0x6e,
	0x65, 0x6d, 0x61, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x64, 0x75, 0x62, 0x62, 0x6f, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72,
	0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x0e, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x2c, 0x0a, 0x0d, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x49, 0x64, 0x22, 0xb5, 0x01,
	0x0a, 0x0d, 0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x63, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x61, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6c,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x03, 0x6c, 0x6f, 0x6e, 0x12, 0x19, 0x0a,
	0x08, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x32, 0x78, 0x0a, 0x06, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x12,
	0x6e, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x2a, 0x2e, 0x64, 0x75, 0x62, 0x62, 0x6f, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2f, 0x2e, 0x64,
	0x75, 0x62, 0x62, 0x6f, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d, 0x61, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x69, 0x6e, 0x65, 0x6d,
	0x61, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_cinema_proto_rawDescOnce sync.Once
	file_cinema_proto_rawDescData = file_cinema_proto_rawDesc
)

func file_cinema_proto_rawDescGZIP() []byte {
	file_cinema_proto_rawDescOnce.Do(func() {
		file_cinema_proto_rawDescData = protoimpl.X.CompressGZIP(file_cinema_proto_rawDescData)
	})
	return file_cinema_proto_rawDescData
}

var file_cinema_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cinema_proto_goTypes = []interface{}{
	(*CinemaResponse)(nil),     // 0: dubbo.CinemaServiceProvider.CinemaResponse
	(*CinemaListResponse)(nil), // 1: dubbo.CinemaServiceProvider.CinemaListResponse
	(*CinemaRequest)(nil),      // 2: dubbo.CinemaServiceProvider.CinemaRequest
	(*RegionRequest)(nil),      // 3: dubbo.CinemaServiceProvider.RegionRequest
}
var file_cinema_proto_depIdxs = []int32{
	0, // 0: dubbo.CinemaServiceProvider.CinemaListResponse.cinema_response:type_name -> dubbo.CinemaServiceProvider.CinemaResponse
	3, // 1: dubbo.CinemaServiceProvider.Cinema.GetCinemaList:input_type -> dubbo.CinemaServiceProvider.RegionRequest
	1, // 2: dubbo.CinemaServiceProvider.Cinema.GetCinemaList:output_type -> dubbo.CinemaServiceProvider.CinemaListResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_cinema_proto_init() }
func file_cinema_proto_init() {
	if File_cinema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cinema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CinemaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CinemaListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CinemaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cinema_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cinema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cinema_proto_goTypes,
		DependencyIndexes: file_cinema_proto_depIdxs,
		MessageInfos:      file_cinema_proto_msgTypes,
	}.Build()
	File_cinema_proto = out.File
	file_cinema_proto_rawDesc = nil
	file_cinema_proto_goTypes = nil
	file_cinema_proto_depIdxs = nil
}
