// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.5
// - protoc             v3.17.2
// source: cinema.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// CinemaClient is the client API for Cinema service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CinemaClient interface {
	GetCinemaList(ctx context.Context, in *RegionRequest, opts ...grpc_go.CallOption) (*CinemaListResponse, common.ErrorWithAttachment)
}

type cinemaClient struct {
	cc *triple.TripleConn
}

type CinemaClientImpl struct {
	GetCinemaList func(ctx context.Context, in *RegionRequest) (*CinemaListResponse, error)
}

func (c *CinemaClientImpl) GetDubboStub(cc *triple.TripleConn) CinemaClient {
	return NewCinemaClient(cc)
}

func (c *CinemaClientImpl) XXX_InterfaceName() string {
	return "dubbo.CinemaServiceProvider.Cinema"
}

func NewCinemaClient(cc *triple.TripleConn) CinemaClient {
	return &cinemaClient{cc}
}

func (c *cinemaClient) GetCinemaList(ctx context.Context, in *RegionRequest, opts ...grpc_go.CallOption) (*CinemaListResponse, common.ErrorWithAttachment) {
	out := new(CinemaListResponse)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetCinemaList", in, out)
}

// CinemaServer is the server API for Cinema service.
// All implementations must embed UnimplementedCinemaServer
// for forward compatibility
type CinemaServer interface {
	GetCinemaList(context.Context, *RegionRequest) (*CinemaListResponse, error)
	mustEmbedUnimplementedCinemaServer()
}

// UnimplementedCinemaServer must be embedded to have forward compatible implementations.
type UnimplementedCinemaServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedCinemaServer) GetCinemaList(context.Context, *RegionRequest) (*CinemaListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCinemaList not implemented")
}
func (s *UnimplementedCinemaServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedCinemaServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedCinemaServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &Cinema_ServiceDesc
}
func (s *UnimplementedCinemaServer) XXX_InterfaceName() string {
	return "dubbo.CinemaServiceProvider.Cinema"
}

func (UnimplementedCinemaServer) mustEmbedUnimplementedCinemaServer() {}

// UnsafeCinemaServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CinemaServer will
// result in compilation errors.
type UnsafeCinemaServer interface {
	mustEmbedUnimplementedCinemaServer()
}

func RegisterCinemaServer(s grpc_go.ServiceRegistrar, srv CinemaServer) {
	s.RegisterService(&Cinema_ServiceDesc, srv)
}

func _Cinema_GetCinemaList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetCinemaList", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// Cinema_ServiceDesc is the grpc_go.ServiceDesc for Cinema service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var Cinema_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "dubbo.CinemaServiceProvider.Cinema",
	HandlerType: (*CinemaServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "GetCinemaList",
			Handler:    _Cinema_GetCinemaList_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "cinema.proto",
}
